name: unified-detection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _py-xgboost-mutex=2.0=gpu_0
  - accelerate=1.4.0=pyhd8ed1ab_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - arrow-cpp=19.0.0=h865e1df_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - blas-devel=3.9.0=12_linux64_mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cpython=3.11.12=py311hd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cudart_linux-64=12.8.57=h3f2d84a_1
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.8.55=hbd13f7d_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.8=h5d125a7_3
  - curl=8.11.1=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.8=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - faiss=1.8.0=py311cuda126h9381f1a_2_cuda
  - faiss-gpu=1.8.0=h0240f8b_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.5.0=py311h5eee18b_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - git=2.45.2=pl5402h72990fb_2
  - git-filter-repo=2.38.0=pyhd8ed1ab_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - huggingface_hub=0.29.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=8.30.0=py311h06a4308_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.5=py311h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=12_linux64_mkl
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.13.0.11=h12f29b5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.9.55=hbd13f7d_0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.4=h5888daf_0
  - libfaiss=1.8.0=cuda120h03f6ba9_1_cuda
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.62.2=h2d74bed_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=hecde1de_4
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.8.55=hbd13f7d_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsentencepiece=0.2.0=hc656cff_4
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.9=h2774228_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=hffd6297_1
  - libudev1=257.3=h9a4d06a_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=2.1.4=cuda128_hacb7753_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.44.0=py311hc1e8f15_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.0=py311h06a4308_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-devel=2021.4.0=h66538d2_640
  - mkl-include=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py311h5eee18b_0
  - mkl_fft=1.3.1=py311h30b3d60_0
  - mkl_random=1.2.2=py311hba01205_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.1.0=py311h5eee18b_0
  - mysql=8.4.0=h29a9f33_1
  - nccl=2.25.1.1=ha44e49d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py311h06a4308_0
  - numba=0.61.2=py311h6220fa4_2
  - numexpr=2.8.4=py311h802d673_0
  - numpy=1.24.3=py311hc206e33_0
  - numpy-base=1.24.3=py311hfd5febd_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.5.4=h26f9b46_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - parso=0.8.4=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - peft=0.14.0=pyhd8ed1ab_0
  - perl=5.40.2=0_h5eee18b_perl5
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=3.10.0=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.4=cuda128_pyh3ef1b53_0
  - pygments=2.15.1=py311h06a4308_1
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=hb806964_0_cpython
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-xxhash=3.5.0=py311h5eee18b_0
  - python_abi=3.11=5_cp311
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qt-main=5.15.2=hb6262e9_11
  - rdma-core=55.0=h5888daf_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h8228510_1
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - responses=0.18.0=pyhd8ed1ab_0
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.6.1=py311h57cc02b_0
  - scipy=1.15.2=py311h8f841c2_0
  - sentencepiece=0.2.0=h38be061_4
  - sentencepiece-python=0.2.0=py311had49c87_4
  - sentencepiece-spm=0.2.0=hc656cff_4
  - setuptools=73.0.1=pyhd8ed1ab_0
  - sip=6.7.12=py311h6a678d5_1
  - six=1.17.0=pyhd8ed1ab_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.13.0=hceb3a55_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py311_cu121
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu121
  - tornado=6.4.2=py311h5eee18b_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - urllib3=2.3.0=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xgboost=2.1.4=cuda128_pyh68bd8d9_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - attrs==25.1.0
      - certifi==2024.12.14
      - datasets==3.3.2
      - et-xmlfile==2.0.0
      - filelock==3.17.0
      - fsspec==2024.12.0
      - multiprocess==0.70.16
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - propcache==0.3.0
      - protobuf==6.30.2
      - psutil==6.1.1
      - pyarrow==19.0.1
      - pytz==2024.2
      - safetensors==0.5.2
      - shap==0.49.1
      - sympy==1.13.1
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - transformers==4.48.1
      - tzdata==2025.1
      - yarl==1.18.3